In [1]:
import numpy as np

In [6]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
arr1.shape

(5,)

In [8]:
arr2=np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
arr2.shape

(2, 2, 2)

In [11]:
arr2.ndim

3

In [14]:
# tells how many elements
arr1.size

5

In [15]:
# tells item size in memory=> 4 for int, 8 for float
arr1.size

5

In [18]:
arr3=np.linspace(10, 20, 10)
arr3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [19]:
arr3.itemsize

8

In [20]:
arr3.dtype

dtype('float64')

In [21]:
arr1.dtype

dtype('int64')

In [22]:
arr1

array([1, 2, 3, 4, 5])

In [24]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [28]:
arr4=np.arange(24).reshape(6,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
arr1

array([1, 2, 3, 4, 5])

In [31]:
arr1[2:5]

array([3, 4, 5])

In [32]:
arr1[2:9]

array([3, 4, 5])

In [33]:
arr1[-1]

np.int64(5)

In [34]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
arr4[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
arr4[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [39]:
arr4[:,2:3]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [40]:
arr4[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [42]:
for i in arr4:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [44]:
for i in np.nditer(arr4):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
